app:
    resource: '@AppBundle/Controller/'
    type: annotation

page:
    resource: '@PageBundle/Controller/'
    type:     annotation
    prefix:   /aisha

inscription:
    resource: '@InscriptionBundle/Controller/'
    type:     annotation
    prefix:   /ecole

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_user:
    resource: "routing_user.yml"

api_web:
    resource: '@InscriptionBundle/Controller/ApiWeb'
    type: annotation
    prefix: /ecole/inscription/apiweb

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"