app:
    resource: '@AppBundle/Controller/'
    type: annotation

page:
    resource: '@PageBundle/Controller/'
    type:     annotation
    prefix:   /aisha

inscription:
    resource: '@InscriptionBundle/Controller/'
    type:     annotation
    prefix:   /admin

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /backoffice

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /backoffice
