services:
#    page.example:
#        class: PageBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    aisha.twig.age:
        class: InscriptionBundle\Twig\AishaExtension
        tags:
          - { name: twig.extension }
