services:
#    page.example:
#        class: PageBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    aisha.twig.age:
        class: InscriptionBundle\Twig\AishaExtension
        tags:
          - { name: twig.extension }

    inscription.admin.enfant:
        class: InscriptionBundle\Admin\EnfantAdmin
        arguments: [~, InscriptionBundle\Entity\Enfant, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Enfant }
        public: true

    inscription.admin.parents:
        class: InscriptionBundle\Admin\ParentsAdmin
        arguments: [~, InscriptionBundle\Entity\Parents, InscriptionBundle:ParentsAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Parents }
        public: true

    inscription.admin.inscrit:
        class: InscriptionBundle\Admin\InscritAdmin
        arguments: [~, InscriptionBundle\Entity\Inscrit, InscriptionBundle:InscritAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Inscrit }
        public: true

    inscription.admin.mensualite:
        class: InscriptionBundle\Admin\MensualiteAdmin
        arguments: [~, InscriptionBundle\Entity\Mensualite, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Mensualite }
        public: true

    inscription.admin.niveau:
        class: InscriptionBundle\Admin\NiveauAdmin
        arguments: [~, InscriptionBundle\Entity\Niveau, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Niveau }
        public: true

    inscription.admin.matiere:
        class: InscriptionBundle\Admin\MatiereAdmin
        arguments: [~, InscriptionBundle\Entity\Matiere, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Matiere }
        public: true
