parameters:
    enfant.manager.class: InscriptionBundle\Services\EnfantManager
    parent.manager.class: InscriptionBundle\Services\ParentManager
    mensualite.manager.class: InscriptionBundle\Services\MensualiteManager
    inscrit.manager.class: InscriptionBundle\Services\InscritManager
    niveau.manager.class: InscriptionBundle\Services\NiveauManager

services:
    aisha.twig.age:
        class: InscriptionBundle\Twig\AishaExtension
        tags:
          - { name: twig.extension }

    enfant_manager:
        class: "%enfant.manager.class%"
        arguments: ['@doctrine.orm.entity_manager']

    parent_manager:
        class: "%parent.manager.class%"
        arguments: ['@doctrine.orm.entity_manager']

    mensualite_manager:
            class: "%mensualite.manager.class%"
            arguments: ['@doctrine.orm.entity_manager']

    inscrit_manager:
           class: "%inscrit.manager.class%"
           arguments: ['@doctrine.orm.entity_manager']

    niveau_manager:
               class: "%niveau.manager.class%"
               arguments: ['@doctrine.orm.entity_manager']