<?php

namespace InscriptionBundle\Repository;

/**
 * EnfantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfantRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $enfant
     * @return array|\Doctrine\ORM\Query
     */
    public function findByClasse($enfant)
    {
        $fiche = $this->getEntityManager()
            ->createQuery('
                    SELECT i
                    FROM InscriptionBundle:Inscrit i 
                    JOIN i.enfant e 
                    JOIN i.niveau n
                    JOIN e.parent p
                    WHERE  e.id = :enfant
                 ');
        $fiche->setParameter('enfant', $enfant);
        return $fiche->getSingleResult();
    }
}
