<?php

namespace InscriptionBundle\Repository;

/**
 * InscritRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscritRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $classe
     * @return mixed
     */
    public function findByEleve($classe)
    {
        $count = $this->getEntityManager()
            ->createQuery('
                    SELECT COUNT(i)
                    FROM InscriptionBundle:Inscrit i 
                    JOIN i.enfant e 
                    JOIN i.niveau n 
                    WHERE n.id = :classe
                 ');
        $count->setParameter('classe', $classe);
        return $count->getSingleScalarResult();
    }

    /**
     * @param $classe
     */
    public function getElevesByNiveau($classe)
    {
        $eleves = $this->getEntityManager()
            ->createQuery('
                    SELECT e.nom, e.prenom, e.dateNaissance, e.genre
                    FROM InscriptionBundle:Inscrit i 
                    JOIN i.enfant e 
                    JOIN i.niveau n 
                    WHERE n.id = :classe
                  ');
        $eleves->setParameter('classe', $classe);
        return $eleves->getResult();
    }

    /**
     * @param $enfant
     * @return array|\Doctrine\ORM\Query
     */
    public function findFicheByEnfant($enfant)
    {
        $fiche = $this->getEntityManager()
            ->createQuery('
                    SELECT i
                    FROM InscriptionBundle:Inscrit i 
                    JOIN i.enfant e 
                    JOIN i.niveau n
                    JOIN e.mensualites m 
                    JOIN e.parent p
                    WHERE  e.id = :enfant
                 ');
        $fiche->setParameter('enfant', $enfant);
        return $fiche->getSingleResult();
    }
}