<?php

namespace InscriptionBundle\Repository;

/**
 * InscritRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscritRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $classe
     * @return mixed
     */
    public function findByEleve($classe)
    {
        $count = $this->getEntityManager()
            ->createQuery('
                    SELECT COUNT(i)
                    FROM InscriptionBundle:Inscrit i 
                    JOIN i.enfant e 
                    JOIN i.niveau n 
                    WHERE n.id = :classe
                 ');
        $count->setParameter('classe', $classe);
        return $count->getSingleScalarResult();
    }

    public function getInscritAll($parent = null)
    {
        $dql = "";
        $dql .= "
             SELECT e.id, e.nom, e.prenom, p.id idP, p.nom pnom, p.prenom pprenom, p.type ptype, n.classe, i.frais, i.paye, i.annee, i.createdAt 
             FROM InscriptionBundle:Inscrit i 
             JOIN i.enfant e 
             JOIN e.parent p
             JOIN i.niveau n
        ";
        if ($parent) {
            $dql .= "WHERE p.id = $parent";
        }
        $query = $this->getEntityManager()
                      ->createQuery($dql);

        return $query->getResult();

    }
}