<?php

namespace InscriptionBundle\Repository;

/**
 * MensualiteNiveauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MensualiteNiveauRepository extends \Doctrine\ORM\EntityRepository
{
}
