<?php

namespace InscriptionBundle\Repository;

/**
 * MensualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MensualiteRepository extends \Doctrine\ORM\EntityRepository
{
}
