<?php

namespace InscriptionBundle\Repository;

/**
 * MensualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MensualiteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $enfant
     * @return array|\Doctrine\ORM\Query
     */
    public function findMensualiteByEnfant($enfant)
    {
        $fiche = $this->getEntityManager()
            ->createQuery('
                    SELECT m
                    FROM InscriptionBundle:Mensualite m
                    JOIN m.enfant e 
                    WHERE  e.id = :enfant
                 ');
        $fiche->setParameter('enfant', $enfant);
        return $fiche->getResult();
    }

    public function findInscritByEnfant($enfantId)
    {
        $inscrit = $this->getEntityManager()
            ->createQuery('
                SELECT i
                FROM InscriptionBundle:Inscrit i 
                JOIN i.enfant e  
                WHERE e.id = :enfant
            ');
        $inscrit->setParameter('enfant', $enfantId);
        return $inscrit->getSingleResult();
    }
}
