<?php

namespace InscriptionBundle\Repository;

/**
 * NiveauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NiveauRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllNiveau($parentId)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("
            SELECT e.id, e.nom, e.prenom, e.dateNaissance, e.genre, n.classe
            FROM InscriptionBundle:Inscrit i 
            LEFT JOIN i.niveau n 
            LEFT JOIN i.enfant e 
            LEFT JOIN e.parent p 
            WHERE p.id = :parent_id
        ");
        $query->setParameter('parent_id', $parentId);
        $result = $query->getResult();

        return $result;
    }

}
