<?php

namespace InscriptionBundle\Repository;

/**
 * NiveauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NiveauRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $classe
     */
    public function findElevesByNiveau($classe)
    {
        $eleves = $this->getEntityManager()
            ->createQuery('
                    SELECT e.id, e.nom, e.prenom, e.dateNaissance, e.genre
                    FROM InscriptionBundle:Inscrit i 
                    JOIN i.enfant e 
                    JOIN i.niveau n 
                    WHERE n.id = :classe
                  ');
        $eleves->setParameter('classe', $classe);
        return $eleves->getResult();
    }
}
