<?php

namespace InscriptionBundle\Repository;

/**
 * ParentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParentRepository extends \Doctrine\ORM\EntityRepository
{
    public function isDeleted($parent)
    {
        return
            $this->createQueryBuilder('p')
                ->join('p.enfants', 'e')
                ->where('p.id= :parent')
                ->setParameter('parent', $parent)
                ->getQuery()
                ->getResult()
        ;
    }

    public function findByParent($parent)
    {
        $em = $this->getEntityManager();

        $query
            = $em->createQuery('
                SELECT e
                FROM InscriptionBundle:Enfant e 
                JOIN e.parent p
                WHERE p.id = :parent
            ');
        $query->setParameter('parent', $parent);
        return $query->getResult();
    }

    public function findByNiveau($parent)
    {
        $em = $this->getEntityManager();

        $query
            = $em->createQuery('
                SELECT e
                FROM InscriptionBundle:Inscrit i 
                JOIN i.enfant e 
                JOIN i.niveau n
                JOIN e.parent p
                WHERE p.id = :parent
            ');
        $query->setParameter('parent', $parent);
        return $query->getResult();
    }
}
